Models
dormroomfund/magic-wand pull request #5
Opened 2019-01-10 05:16 UTC by VinaiRachakonda

Setup the models and their relations.

2019-01-10 05:17 UTC, casey-chow requested changes
Let's offload the JSON schemas elsewhere (i.e. client side or a shared folder), otherwise LGTM.

2019-01-10 17:11 UTC, casey-chow approved these changes

2019-01-14 00:03 UTC, casey-chow commented on shared/schema.js
> +/*
Design decision: I've tried very hard to client-side validate using JSON schemas, and it's surprisingly difficult to get useful validation data out of ajv (despite what everyone says online). I have found [yup](https://github.com/jquense/yup) to be very useful, and have developed snippets to enable validation at a Feathers level. That said, JSON schemas are probably a lot more flexible. Wdyt?

(In any case, I think it'd be good to move the validation to a [hook](https://feathers-plus.github.io/v1/feathers-hooks-common/#validateschema)--this centralizes the business logic to hooks, so it's easier to find things imo.)

2019-01-15 18:04 UTC, VinaiRachakonda commented on shared/schema.js
> +/*
I'll create a separate pr for moving validation to a hook.

2019-01-15 18:05 UTC, merged